/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OpensourceRouteImport } from './routes/opensource'
import { Route as CaseRouteImport } from './routes/case'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const OpensourceRoute = OpensourceRouteImport.update({
  id: '/opensource',
  path: '/opensource',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseRoute = CaseRouteImport.update({
  id: '/case',
  path: '/case',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/case': typeof CaseRoute
  '/opensource': typeof OpensourceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/case': typeof CaseRoute
  '/opensource': typeof OpensourceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/case': typeof CaseRoute
  '/opensource': typeof OpensourceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/case' | '/opensource'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/case' | '/opensource'
  id: '__root__' | '/' | '/about' | '/case' | '/opensource'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CaseRoute: typeof CaseRoute
  OpensourceRoute: typeof OpensourceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/opensource': {
      id: '/opensource'
      path: '/opensource'
      fullPath: '/opensource'
      preLoaderRoute: typeof OpensourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case': {
      id: '/case'
      path: '/case'
      fullPath: '/case'
      preLoaderRoute: typeof CaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CaseRoute: CaseRoute,
  OpensourceRoute: OpensourceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
